---
- name: 'Create mount of log files on remote sstone for weblogic servers'
  hosts: all
  gather_facts: False

  vars: 
    - config_file: "{{ '/etc/auto.weblogic' if prod is defined else '/etc/auto.cndev' }}"

  tasks:
    - name: 'Create variable of environment cz/cn'
      set_fact:
        env: "{{ inventory_hostname_short | regex_search('([^-]*$)')}}"

    - name: 'Entry comment of env in sstone server'
      lineinfile:
        path: "{{ config_file }}"
        line: "## {{ env }} ##"
      delegate_to: "{{ sstone_server }}"
    
    - name: 'Managed by Ansible comment'
      lineinfile:
        path: "{{ config_file }}"
        line: "# This file is managed by Ansible "
        insertbefore: BOF
      delegate_to: "{{ sstone_server }}"  
      
    - name: 'Entry comment in /etc/exports'
      lineinfile:
        path: /etc/exports
        line: "# Exports to sstone are Ansible managed"
        insertbefore: BOF
        
    # Include playbook for:
    # 1) Exporting directories on hosts
    # 2) Mounting directories on logging server
    # 3) Run playbook for every directory
    - include_tasks: tasks/ExportAndMount.yml
      with_items: "{{ directories }}"


    # Restart of NFS services on host and autofs service on logging server
    - name: 'Restart NFS service on localhost'
      service:
        name: nfs
        state: restarted

    - name: 'Restart autofs service on logging server'
      service:
        name: autofs
        state: restarted
      delegate_to: "{{ sstone_server }}"
